services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ../src/backend
      dockerfile: DistributedTaskScheduler.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  worker-email:
    build:
      context: ../src/backend
      dockerfile: DistributedTaskScheduler.Worker/Dockerfile
    command: ["Email"]
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker-fileprocessing:
    build:
      context: ../src/backend
      dockerfile: DistributedTaskScheduler.Worker/Dockerfile
    command: ["FileProcessing"]
    depends_on:
      rabbitmq:
        condition: service_healthy
