services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: ../src/backend
      dockerfile: DistributedTaskScheduler.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  worker-email:
    build:
      context: ../src/backend
      dockerfile: DistributedTaskScheduler.Worker/Dockerfile
    command: ["Email"]
    depends_on:
      - rabbitmq

  worker-fileprocessing:
    build:
      context: ../src/backend
      dockerfile: DistributedTaskScheduler.Worker/Dockerfile
    command: ["FileProcessing"]
    depends_on:
      - rabbitmq
